---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vcluster-with-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-36"
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: infra.pro-techt.io/v1alpha1
    kind: VCluster

  mode: Pipeline

  pipeline:
    - step: render-vcluster-resources
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: github.com/aigineering/argo-cluster-boot/kcl4

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
