---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vcluster-with-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-36"
spec:
  compositeTypeRef:
    apiVersion: infra.pro-techt.io/v1alpha1
    kind: VCluster

  mode: Pipeline

  pipeline:
    - step: render-vcluster-resources
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: basic
        spec:
          dependencies:
            - '{ git = "https://github.com/SimSimY/kcl-vcluster-config", commit = "3af8de0", version = "0.30.0" }'
            - 'argo-cd = "3.1.8"'
            - 'crossplane-provider-kubernetes = "0.18.0"'
          target: Resources

          source: |
            import argo_cd.v1alpha1
            import crossplane_provider_kubernetes.v1alpha2
            import yaml
            import vcluster_config.models.values as vc
            import models.v1alpha1.infra_pro_techt_io_v1alpha1_v_cluster as vcluster

            # oxr = option("params").oxr
            _config = vcluster.VCluster {
                metadata: {
                    name: "testss"
                    namespace: "default"
                }
                spec: {
                    parameters: {
                        clusterName: "test-cluster"
                        exportConfig: {
                            name: "tests-secret"
                            namespace: "somens"
                        }
                    }
                }
            }
            _spec = _config.spec.parameters

            _CC = vc.ClusterConfig {
                exportKubeConfig: {
                    secret: {
                        name: _spec.exportConfig.name
                        namespace: _spec.exportConfig.namespace
                    }
                }
            }
            v1alpha1.Application {
                metadata: {
                    name: "vcluster-" + _config.metadata.name
                    namespace: "argocd"
                }
                spec: {
                    project: "default"
                    source: {
                        repoURL: "https://charts.loft.sh"
                        chart: "vcluster"
                        targetRevision: _spec.vclusterHelmVersion
                        helm: {
                            values: yaml.encode(_CC)
                        }
                    }
                    destination: {
                        server: "https://kubernetes.default.svc"
                        namespace: "vcluster"
                    }
                    syncPolicy: {
                        automated: {
                            prune: False
                            selfHeal: True
                        }
                    }
                }
            }
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
