apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-11-15T22:45:28Z"
  generation: 3
  name: vclusters.infra.pro-techt.io
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CompositeResourceDefinition
    name: vclusters.infra.pro-techt.io
    uid: fda58c7d-eaca-4a56-a03b-8d49b6c7e506
  resourceVersion: "101485"
  uid: 8802db11-3993-4c88-b58a-050bce4a59f8
spec:
  conversion:
    strategy: None
  group: infra.pro-techt.io
  names:
    categories:
    - composite
    kind: VCluster
    listKind: VClusterList
    plural: vclusters
    singular: vcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.crossplane.compositionRef.name
      name: COMPOSITION
      type: string
    - jsonPath: .spec.crossplane.compositionRevisionRef.name
      name: COMPOSITIONREVISION
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            properties:
              crossplane:
                description: Configures how Crossplane will reconcile this composite
                  resource
                properties:
                  compositionRef:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  compositionRevisionRef:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  compositionRevisionSelector:
                    properties:
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - matchLabels
                    type: object
                  compositionSelector:
                    properties:
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - matchLabels
                    type: object
                  compositionUpdatePolicy:
                    default: Automatic
                    enum:
                    - Automatic
                    - Manual
                    type: string
                  resourceRefs:
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                      required:
                      - apiVersion
                      - kind
                      type: object
                    type: array
                    x-kubernetes-list-type: atomic
                type: object
              parameters:
                properties:
                  clusterName:
                    description: Name of the vcluster
                    type: string
                  exportConfig:
                    description: Kubeconfig export configuration
                    properties:
                      name:
                        description: Name of the secret to store the kubeconfig
                        type: string
                      namespace:
                        description: Namespace of the secret to store the kubeconfig
                        type: string
                    type: object
                  expose:
                    default:
                      annotations: {}
                      type: LoadBalancer
                    description: Service exposure configuration for accessing the
                      vcluster
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        default: {}
                        type: object
                      type:
                        default: LoadBalancer
                        enum:
                        - LoadBalancer
                        - NodePort
                        - ClusterIP
                        type: string
                    type: object
                  kubernetes:
                    default:
                      version: "1.33"
                    description: Kubernetes configuration for the vcluster
                    properties:
                      version:
                        default: "1.33"
                        description: Kubernetes version for the vcluster
                        type: string
                    type: object
                  namespace:
                    default: vcluster
                    description: Namespace where the vcluster will be deployed
                    type: string
                  resources:
                    default:
                      controlPlane:
                        limits:
                          cpu: 1000m
                          memory: 1Gi
                        requests:
                          cpu: 200m
                          memory: 256Mi
                      syncer:
                        limits:
                          cpu: 500m
                          memory: 512Mi
                        requests:
                          cpu: 100m
                          memory: 128Mi
                    description: Resource limits and requests for vcluster components
                    properties:
                      controlPlane:
                        properties:
                          limits:
                            properties:
                              cpu:
                                default: 1000m
                                type: string
                              memory:
                                default: 1Gi
                                type: string
                            type: object
                          requests:
                            properties:
                              cpu:
                                default: 200m
                                type: string
                              memory:
                                default: 256Mi
                                type: string
                            type: object
                        type: object
                      syncer:
                        properties:
                          limits:
                            properties:
                              cpu:
                                default: 500m
                                type: string
                              memory:
                                default: 512Mi
                                type: string
                            type: object
                          requests:
                            properties:
                              cpu:
                                default: 100m
                                type: string
                              memory:
                                default: 128Mi
                                type: string
                            type: object
                        type: object
                    type: object
                  vclusterHelmVersion:
                    default: 0.30.0
                    description: Version of vcluster to deploy
                    type: string
                required:
                - clusterName
                type: object
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              endpoint:
                description: The endpoint URL of the vcluster API server
                type: string
              ready:
                description: Whether the vcluster is ready
                type: boolean
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - composite
    kind: VCluster
    listKind: VClusterList
    plural: vclusters
    singular: vcluster
  conditions:
  - lastTransitionTime: "2025-11-15T22:45:28Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-11-15T22:45:28Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
